name: "My Custom Action"
description: "A custom GitHub Action example"
inputs:
  name:
    description: "Name of the user"
    required: true
    default: "World"
runs:
  using: "node16"
  main: "index.js"
