name: Test My Custom Action
# 스케줄 방식
on:
  schedule:
    - cron: '*/5 * * * *' # 매분 
  workflow_dispatch:
jobs:
  echo-test:
    runs-on: ubuntu-latest
    steps:
      - name: Step1) Checkout code
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
        
      - name: Step2) Print current date and custom message
        run: |
          echo "This is a scheduled test!"
          echo "Current Date and Time: $(date)"
        
      - name: Step3) Run custom action
        uses: ./
        with:
          name: "GGG"
          name2: "GGG2"