name: Test My Custom Action
# 스케줄 방식
on:
  schedule:
    - cron: '*/5 * * * *' # 매분 
  workflow_dispatch:
jobs:
  echo-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@3
        
      - name: Run custom action
        uses: ./
        with:
          name: "GGG"
      - name: Print current date and custom message
        run: |
          echo "This is a scheduled test!"
          echo "Current Date and Time: $(date)"
