name: Codespace Scheduler

on:
  # schedule:
  #   - cron: '*/5 * * * *' 
  workflow_dispatch:
jobs:
  codespace_scheduler:
    runs-on: ubuntu-latest
    steps:
      - name: Codespace Scheduler
        uses: ud803/github-codespace-scheduler@v1.0.6
        env:
          GITHUB_AUTH: ${{ secrets.TOKEN_CODESPACE }}
        with:
          CODESPACE_NAME: "fictional-parakeet-wvpw6rp5grg3g57j"
          WAIT_SECONDS: 30
