name: Test My Custom Action
# 스케줄 방식
on:
  schedule:
    - cron: '*/5 * * * *' # 매분 
  workflow_dispatch:
jobs:
  echo-test:
    runs-on: ubuntu-latest
    steps:
      - name: Step1) Checkout code
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
        
      - name: Step2) Print current date and custom message
        run: |
          echo "This is a scheduled test!"
          echo "Current Date and Time: $(date)"
        
      - name: Step3) Start Codespace
        env:
          github_auth: ${{ secrets.TOKEN_CODESPACE }}
          PR_NUMBER: ${{ github.event.number }}
        uses: ./run1_start_codespace.yml
        with:
          name: "GGG"
          repo_id: 897314120
          CODESPACE_NAME: "fictional-parakeet-wvpw6rp5grg3g57j"

      - name: Step4) Wait for a sec
        run: sleep 10

      - name: Step5) Stop Codespace
        env:
          github_auth: ${{ secrets.TOKEN_CODESPACE }}
          PR_NUMBER: ${{ github.event.number }}
        uses: ./run2_stop_codespace.yml
        with:
          name: "GGG"
          repo_id: 897314120
          CODESPACE_NAME: "fictional-parakeet-wvpw6rp5grg3g57j"
