name: Test My Custom Action
# 스케줄 방식
on:
  schedule:
    - cron: '* * * * *' # 매분 실행
jobs:
  echo-test:
    runs-on: ubuntu-latest
    steps:
      - name: Print current date and custom message
        run: |
          echo "This is a scheduled test!"
          echo "Current Date and Time: $(date)"
